apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
      app: scheduler
      phase: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
        tier: backend
        phase: test
    spec:
      containers:
      - name: scheduler-container
        image: boomzero/night-watch:scheduler
        ports:
        - containerPort: 3010
        imagePullPolicy: Always
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: database
              key: MONGODB_URI
        - name: MONGODB_DB_NAME
          value: "scheduler"
        - name: MONGODB_URI
          value: "$(DB_URI)$(MONGODB_DB_NAME)"
